### ISSUE TITLE
Bubble Sort script and documentation

### ISSUE THREAD

**Issue by Zircoz** [Zircoz/Sorting-Algorithms-in-Python#1]
Write a neat program for Bubble sort in python with a clear and helpful documentation.

**Comment by SaxenaKartik** [comment]
I would like to work on this

**Comment by Zircoz** [comment]
@SaxenaKartik Sure, fork it and create a PR when done. All the best.

**Comment by subhadeep-deyashi** [comment]
What is an appropriate issue number?

**Comment by Zircoz** [comment]
> 
> 
> What is an appropriate issue number?

I think you know now.

**Comment by Zircoz** [comment]
@crandalj I may not notice if you make PR for anything until you mention me or refer the issue in it.

Now, if @SaxenaKartik doesn't complete the changes requested in next 2 days, I will reopen your PR #7  and approve it purely on its merit of being more useful. And because he requested to take upon this issue first.

**Comment by subhadeep-deyashi** [comment]
Actually it was my first ever PR. I didn't know anything about these at all
and I'm more than happy that my contribution whether useful or not is
atleast acknowledged. Thanks a lot.

**Comment by Zircoz** [comment]
OKay @subhadeep-deyashi , no worries.
This repo is made to help first timers.

I think you will find this useful: https://www.digitalocean.com/community/tutorial_series/an-introduction-to-open-source

**Comment by Zircoz** [comment]
@SaxenaKartik made the changes requested so I am closing this issue now, for submitting any improvements to the code create new issue.

CC: @subhadeep-deyashi @crandalj
