### ISSUE TITLE
Selection Sort program and documentation

### ISSUE THREAD

**Issue by shriyaMadan** [Zircoz/Sorting-Algorithms-in-Python#12]

**Comment by shriyaMadan** [comment]
I wanna do it @Zircoz

**Comment by Zircoz** [comment]
Would love to see your work @shriyaMadan

**Comment by Zircoz** [comment]
This has been completed but it takes an array of numbers separated by whitespaces. If anyone can make it more 'user-friendly' it will be great!

**Comment by dwijenchawra** [comment]
I'd like to work on this!
