### ISSUE TITLE
Quick Sort script and documentation

### ISSUE THREAD

**Issue by Zircoz** [Zircoz/Sorting-Algorithms-in-Python#3]
Write a neat program implementing quick sort in python with a clear and helpful documentation.

**Comment by khanaaziz1** [comment]
i can contribute

**Comment by Zircoz** [comment]
> 
> 
> i can contribute

Would love to see your work at it @khanaaziz1 !

**Comment by khanaaziz1** [comment]
ready for your review

**Comment by akhilkh2000** [comment]
Can i contribute?

**Comment by piyushsinha24** [comment]
issue still open??? can I contribute?

**Comment by Zircoz** [comment]
@akhilkh2000 @piyushsinha24 Sorry guys, @khanaaziz1 was assigned to it and he already did it.
If you can improve upon his work, let me know here.
