### ISSUE TITLE
Insertion Sort script and documentation

### ISSUE THREAD

**Issue by Zircoz** [Zircoz/Sorting-Algorithms-in-Python#5]

**Comment by akhilkh2000** [comment]
Can i take up this issue?

**Comment by Zircoz** [comment]
Hey @akhilkh2000 , @eric3119 already submitted a PR for this issue.
So, if you can improve upon his code/documentation please do it. Also, preferably explain how your (proposed?) changes improve the existing version.

**Comment by Zircoz** [comment]
@24sharkS You didn't mention this issue or me anywhere on your PR ( #11 ). In conditions like these, I may not know that you created a PR (considering there are so many of them).

Plus, Eric already got his commits merged, so now an improvement will be much appreciated.

**Comment by 24sharkS** [comment]
@Zircoz, I would surely like to work on improving it.

**Comment by Zircoz** [comment]
Sure, @24sharkS Create a new issue when you decide to do it.
